### ISSUE TITLE
CNC Pendant compatibility

### ISSUE THREAD

**Issue by FelixHauser** [technik-gegg/SMuFF-Ifc#2]
Hi there,

I am not interested in the SMuFF application of this project, but it has been pointed out to me on the Duet Forums that this could be useful to simultaneously use a Panel Due with a CNC Pendant, which it just streams GCode to the Duet board.
Would it be possible on the current state of the project or there is something to be tweaked, software base, I mean?

thanks in advance

**Comment by technik-gegg** [comment]
I'm not sure I fully understand your question. Can you depict a bit more in detail how you'd connect those components and who streams the GCode to whom?

**Comment by FelixHauser** [comment]
sorry if I wasn't clear. From the beginning:
I have a Duet driven CNC machine. Since this machine generates a lot of dust I have it far away from my printers and computers. Therefore I am using the Panel Due display to jog the tool, probe the stock, start jobs, etc. Although a bit cumbersome because the PanelDue display is designed with 3d Printing in mind, it's quite useful as I don't need a computer nearby. The only problem (for me) is jog the tool. The interface is not optimal. To overcome this, the people from Duet are working on a CNC [Pendant](https://www.google.com/search?q=cnc+pendant&client=firefox-b-d&sxsrf=ALeKk02Tz4A7SfnU0epwN3kfcuitbq8rZA:1588961455313&tbm=isch&source=iu&ictx=1&fir=nVqkMBWir8OCCM%253A%252ChW9mopTv2GmuSM%252C_&vet=1&usg=AI4_-kTWHHXrVGuRgEroiHEBbGm76XYD9A&sa=X&ved=2ahUKEwiI8OvY7qTpAhWHSRUIHfVxD4MQ9QEwAHoECAkQGw#imgrc=nVqkMBWir8OCCM:) to make it easier. This pendant will be Arduino-based and it will send Gcode via the PanelDue port on the Duet, so that you have to chose: either you want the Display or you want the Pendant. Somebody on [this thread](https://forum.duet3d.com/topic/11389/cnc-style-pendant/32?_=1588941967888) on the Duet Forum pointed me to your project, which theoretically  would allow having the Display and the Pendant simultaneously.

Now, my question is: would it be possible "out of the box" where or would I need to modify some code?

**Comment by technik-gegg** [comment]
That's much clearer now and almost what I thought it'd be.

Right away: Yes, it's possible. The SMuFF-Ifc is just (in this case a bit over engineered) 3 way splitter.
It maintains the communication between Duet and Panel Due and the SMuFF, or in your case the pendant.
The only requirements are: The pendants interface has to be TTL not RS-232 and it is only sending GCode, which, if I'm right, is the case in your scenario.
You could also send messages (GCodes) to the pendant from the Duet, but you have to escape then (by preceeding a "\s" to the message).
What you can't do is sending messages from the PanelDue directly to the Pendant.

However, as this pendent is in development right now (if I got that correctly), why would you need the SMuFF-Ifc? Ain't it easier to add the same functionality to the Arduino code - that is assuming that the Arduino in charge has 3 serial ports available?

**Comment by FelixHauser** [comment]
well, the pendant I've got has no screen. It's actually just a collection of knobs and a rotary encoder, so no need to send info there.
I really do not know what the development looks like on that interface. DC42 back on the Duet site will be publishing it on GitHub when ready. I do not know if it is TTL or RS-232... to be honest I do not know anything about the topic of communications, so I could not tell even if I had the code in front of me.

Obviously doing a single arduino solution would be optimal for me, but apparently I might be the only one using a PanelDue display on a CNC machine...

**Comment by technik-gegg** [comment]
I quote from the code comment in the thread you mentioned:

> // Duet2_CNC_Pendant
// Intended to run on an ESP32 and interface hardware pendant to Duet3d/RepRap
// controller via TTL serial at 3.3V. Intended to run "in parallel" or "in place"
// of a PanelDue. 
// Example pendants can be found on E-bay; must have individual wires (not usb).
 
So, you're supposed to be save on that topic.

Well, in this case: Go for the SMuFF-Ifc I'd say ;o)

**Comment by FelixHauser** [comment]
well... it is a long thread... :-)

Thanks for your input!
